# Generated by Django 6.0.2 on 2026-03-12 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groupbuy", "0002_dedupe_orders_and_unique_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="groupbuy",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Food", "Food"),
                    ("Grocery", "Grocery"),
                    ("Stationery", "Stationery"),
                    ("Other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="groupbuy",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupbuy",
            name="pickup_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupbuy",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("ordered", "Ordered"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="groupbuy",
            name="store_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="groupbuy",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="GroupBuyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groupbuy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="groupbuy.groupbuy",
                    ),
                ),
            ],
        ),
    ]
